/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Robi
 * Created: 10-mag-2017
 */

/* nome db:ammdb  nome utente: nerd  password: nerd */

/*tabella relativa agli utenti*/
CREATE TABLE utente(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    email VARCHAR(256),
    password VARCHAR(256),
    urlProfilo VARCHAR(256),
    dataNascita DATE,
    presentazione VARCHAR(256)
);

/*Creo la tabella relativa al tipo di url: IMAGE, LINK, NULL*/
CREATE TABLE tipoUrl(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo INTEGER
);

/*Creazione della tabella dei post*/
CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES utente(id),
    contentText VARCHAR(32),
    url VARCHAR(32),
    tipoPost INTEGER,
    FOREIGN KEY (tipoPost) REFERENCES tipoUrl(id)
);

/*Creazione della tabella dei gruppi*/
CREATE TABLE gruppo(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    amministratore INTEGER,
    FOREIGN KEY (amministratore) REFERENCES utente(id)
);

/*Creazione una tabella relativa agli utenti per ogni gruppo*/
CREATE TABLE utentePerOgniGruppo(
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES utente(id),
    gruppo INTEGER,
    PRIMARY KEY (utente, gruppo)
);
/*DA FARE*/
INSERT INTO utente (id, nome, cognome, email, password, urlProfilo, dataNascita, presentazione)
VALUES (0,
        'Mario',
        'Bros',
        'mariobros@gmail.com',
        '0000',
        'img/SuperMario.jpg',
        '1900-03-10',
        'Ciao, sono Mario!'),
        (1,
        'Neo',
        'Cortex',
        'cortex@gmail.com',
        '9001',
        'img/neocortex.jpg',
        '1930-12-04',
        'Ciao, sono Cortex e sono un super cattivo! Mhuahahahah'),

        );